In [1]:
import sys

In [2]:
sys.path

['C:\\Users\\e015614\\OneDrive - FBL Financial Group, Inc\\CAS Python Course',
 'C:\\Users\\e015614\\Anaconda3\\python37.zip',
 'C:\\Users\\e015614\\Anaconda3\\DLLs',
 'C:\\Users\\e015614\\Anaconda3\\lib',
 'C:\\Users\\e015614\\Anaconda3',
 '',
 'C:\\Users\\e015614\\Anaconda3\\lib\\site-packages',
 'C:\\Users\\e015614\\Anaconda3\\lib\\site-packages\\win32',
 'C:\\Users\\e015614\\Anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\e015614\\Anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\Users\\e015614\\Anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\e015614\\.ipython']

In [4]:
sys.path.append("\OneDrive - FBL Financial Group, Inc\\CAS Python Course")

<function dir>

In [6]:
d = cas_demo.Demo("Session2.md")

NameError: name 'cas_demo' is not defined

In [8]:
a = [1,2,3,4,6]

a[1], a[3:], a[-2], a[-2:], a[::-1]

(2, [4, 6], 4, [4, 6], [6, 4, 3, 2, 1])

In [9]:
def myfunction(x):
    return x * 10

myfunction(20)

200

In [10]:
s = "jack and jill went up the hill to fetch a pail of water "

In [11]:
{ i : s.count(i) for i in set(s) }

{'t': 5,
 'l': 5,
 'k': 1,
 'u': 1,
 'o': 2,
 'a': 5,
 'i': 3,
 'd': 1,
 'h': 3,
 'r': 1,
 'j': 2,
 'p': 2,
 'w': 2,
 ' ': 13,
 'n': 2,
 'e': 4,
 'f': 2,
 'c': 2}

In [14]:
def letter(s, omit=''):
    return { i : s.count(i) for i in set(s) if i not in omit }

letter(s)

{'t': 5,
 'l': 5,
 'k': 1,
 'u': 1,
 'o': 2,
 'a': 5,
 'i': 3,
 'd': 1,
 'h': 3,
 'r': 1,
 'j': 2,
 'p': 2,
 'w': 2,
 ' ': 13,
 'n': 2,
 'e': 4,
 'f': 2,
 'c': 2}

In [13]:
letter(s, ' aeiou')

{'t': 5,
 'l': 5,
 'k': 1,
 'd': 1,
 'h': 3,
 'r': 1,
 'j': 2,
 'p': 2,
 'w': 2,
 'n': 2,
 'f': 2,
 'c': 2}

In [15]:
print(s.split())

['jack', 'and', 'jill', 'went', 'up', 'the', 'hill', 'to', 'fetch', 'a', 'pail', 'of', 'water']


In [16]:
letter(s.split())

{'and': 1,
 'up': 1,
 'the': 1,
 'went': 1,
 'a': 1,
 'pail': 1,
 'fetch': 1,
 'water': 1,
 'of': 1,
 'to': 1,
 'hill': 1,
 'jill': 1,
 'jack': 1}

In [17]:
dir(str) #all you can do about function

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',


In [18]:
s.title()

'Jack And Jill Went Up The Hill To Fetch A Pail Of Water '

In [19]:
def sdir(x, colwidth=80):
    """
    Directory of useful elements, wrapped
    """
    from textwrap import fill

    # all the work is in this line:
    l = [i for i in dir(x) if i[0] != '_']

    # frills to printout nicely
    mx = max(map(len, l))
    mx += 2
    fs = f'{{:<{mx:d}s}}'
    l = [fs.format(i) for i in l if i[0] != '_']
    print(fill('\t'.join(l), colwidth))

In [20]:
sdir(str)

capitalize      casefold        center          count           encode
endswith        expandtabs      find            format          format_map
index           isalnum         isalpha         isascii         isdecimal
isdigit         isidentifier    islower         isnumeric       isprintable
isspace         istitle         isupper         join            ljust
lower           lstrip          maketrans       partition       replace
rfind           rindex          rjust           rpartition      rsplit
rstrip          split           splitlines      startswith      strip
swapcase        title           translate       upper           zfill


In [22]:
?str.strip()

Object `str.strip()` not found.


In [23]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [24]:
import numpy as np

In [25]:
sdir(np.random)

BitGenerator            Generator               MT19937                 PCG64
Philox                  RandomState             SFC64
SeedSequence            absolute_import         beta                    binomial
bytes                   chisquare               choice
default_rng             dirichlet               division
exponential             f                       gamma
geometric               get_state               gumbel
hypergeometric          laplace                 logistic
lognormal               logseries               mtrand
multinomial             multivariate_normal     negative_binomial
noncentral_chisquare    noncentral_f            normal                  pareto
permutation             poisson                 power
print_function          rand                    randint                 randn
random                  random_integers         random_sample           ranf
rayleigh                sample                  seed
set_state               shuffle                

In [26]:
r_letters = np.random.choice(list('ABCDE'), 10)

In [28]:
r_letters

array(['D', 'E', 'D', 'D', 'D', 'C', 'D', 'B', 'B', 'B'], dtype='<U1')

In [29]:
r_unif = np.random.rand(10)
r_unif 

array([0.41275169, 0.14408703, 0.19666275, 0.25897569, 0.38059331,
       0.93563232, 0.68031718, 0.15016898, 0.80338865, 0.19411399])

In [30]:
r_lognorm = np.random.lognormal(10, .2, 10)
r_lognorm

array([20199.9678523 , 42100.14074233, 18588.56712059, 25285.75826367,
       26000.60560461, 27853.06767908, 22909.8560586 , 23081.69361154,
       18387.48422912, 22786.39787686])

In [31]:
r_letters, r_unif, r_lognorm

(array(['D', 'E', 'D', 'D', 'D', 'C', 'D', 'B', 'B', 'B'], dtype='<U1'),
 array([0.41275169, 0.14408703, 0.19666275, 0.25897569, 0.38059331,
        0.93563232, 0.68031718, 0.15016898, 0.80338865, 0.19411399]),
 array([20199.9678523 , 42100.14074233, 18588.56712059, 25285.75826367,
        26000.60560461, 27853.06767908, 22909.8560586 , 23081.69361154,
        18387.48422912, 22786.39787686]))

In [32]:
f_letters = np.random.choice(list('ABCDEf'), 10)
f_letters 

array(['f', 'f', 'B', 'B', 'C', 'f', 'f', 'B', 'B', 'D'], dtype='<U1')

In [33]:
letters = list(np.random.choice(list('ABCDE'), 500, p=[.4,.3,.2,.05,.05]))
n = len(letters)
n

500

In [34]:
freq = { i: letters.count(i) / n for i in 'ABCDE'}

freq

{'A': 0.396, 'B': 0.272, 'C': 0.22, 'D': 0.054, 'E': 0.058}

In [ ]:
Module 2: Create a DataFrame and Access Elements
Finally, Pandas: your spreadsheet in Python.

In [35]:
import pandas as pd

df  = pd.DataFrame({'a': range(100, 110),
                    'b' : np.random.choice(list('ABCDEF'), 10),
                    'c' : np.random.rand(10),
                    'd': pd.to_datetime('2020/07/05')+pd.to_timedelta(np.arange(10), unit='D')
                    })
df

a  b         c          d
0  100  C  0.002056 2020-07-05
1  101  A  0.952524 2020-07-06
2  102  E  0.960452 2020-07-07
3  103  C  0.256880 2020-07-08
4  104  C  0.404484 2020-07-09
5  105  C  0.369257 2020-07-10
6  106  D  0.615223 2020-07-11
7  107  B  0.148601 2020-07-12
8  108  B  0.707396 2020-07-13
9  109  E  0.222646 2020-07-14

In [36]:
print(df)

     a  b         c          d
0  100  C  0.002056 2020-07-05
1  101  A  0.952524 2020-07-06
2  102  E  0.960452 2020-07-07
3  103  C  0.256880 2020-07-08
4  104  C  0.404484 2020-07-09
5  105  C  0.369257 2020-07-10
6  106  D  0.615223 2020-07-11
7  107  B  0.148601 2020-07-12
8  108  B  0.707396 2020-07-13
9  109  E  0.222646 2020-07-14


In [37]:
df.dtypes

a             int64
b            object
c           float64
d    datetime64[ns]
dtype: object

In [38]:
df['a']

0    100
1    101
2    102
3    103
4    104
5    105
6    106
7    107
8    108
9    109
Name: a, dtype: int64

In [39]:
df.a

0    100
1    101
2    102
3    103
4    104
5    105
6    106
7    107
8    108
9    109
Name: a, dtype: int64

In [40]:
#Accessing Data within a DataFrame: Row Index
df.loc[3]

a                    103
b                      C
c                0.25688
d    2020-07-08 00:00:00
Name: 3, dtype: object

In [41]:
#Accessing Data Within a DataFrame: Row and Column Index
df.loc[3, 'd']

Timestamp('2020-07-08 00:00:00')

In [43]:
df.loc[::2]

a  b         c          d
0  100  C  0.002056 2020-07-05
2  102  E  0.960452 2020-07-07
4  104  C  0.404484 2020-07-09
6  106  D  0.615223 2020-07-11
8  108  B  0.707396 2020-07-13

In [44]:
#Accessing Data Within a DataFrame: Logic
df.a < 105

0     True
1     True
2     True
3     True
4     True
5    False
6    False
7    False
8    False
9    False
Name: a, dtype: bool

In [45]:
#Accessing Data Within a DataFrame: Logic
df.loc[df.a < 105]

a  b         c          d
0  100  C  0.002056 2020-07-05
1  101  A  0.952524 2020-07-06
2  102  E  0.960452 2020-07-07
3  103  C  0.256880 2020-07-08
4  104  C  0.404484 2020-07-09

In [46]:
#Accessing Data Within a DataFrame: The Query Operator
#Very powerful, very fast

#SQL like

#ccess elements with @

df.query(' .4 < c < .8 ')

a  b         c          d
4  104  C  0.404484 2020-07-09
6  106  D  0.615223 2020-07-11
8  108  B  0.707396 2020-07-13

In [48]:
#Add Data
#Create new columns with math, from old columns

#Create new row

#Can't create on the fly like tidyverse


df['E'] = df.a / df.c
df

a  b         c          d             E
0  100  C  0.002056 2020-07-05  48632.335790
1  101  A  0.952524 2020-07-06    106.034037
2  102  E  0.960452 2020-07-07    106.200021
3  103  C  0.256880 2020-07-08    400.965553
4  104  C  0.404484 2020-07-09    257.117792
5  105  C  0.369257 2020-07-10    284.354928
6  106  D  0.615223 2020-07-11    172.295125
7  107  B  0.148601 2020-07-12    720.050346
8  108  B  0.707396 2020-07-13    152.672633
9  109  E  0.222646 2020-07-14    489.565612

In [49]:
df.loc[100, :] = (110, 'Z', .11223344, pd.to_datetime('2020/11/03'), np.nan)

In [50]:
display(df)

a  b         c          d             E
0    100.0  C  0.002056 2020-07-05  48632.335790
1    101.0  A  0.952524 2020-07-06    106.034037
2    102.0  E  0.960452 2020-07-07    106.200021
3    103.0  C  0.256880 2020-07-08    400.965553
4    104.0  C  0.404484 2020-07-09    257.117792
5    105.0  C  0.369257 2020-07-10    284.354928
6    106.0  D  0.615223 2020-07-11    172.295125
7    107.0  B  0.148601 2020-07-12    720.050346
8    108.0  B  0.707396 2020-07-13    152.672633
9    109.0  E  0.222646 2020-07-14    489.565612
100  110.0  Z  0.112233 2020-11-03           NaN

In [51]:
df['F']=df.E*df.c
df

a  b         c          d             E      F
0    100.0  C  0.002056 2020-07-05  48632.335790  100.0
1    101.0  A  0.952524 2020-07-06    106.034037  101.0
2    102.0  E  0.960452 2020-07-07    106.200021  102.0
3    103.0  C  0.256880 2020-07-08    400.965553  103.0
4    104.0  C  0.404484 2020-07-09    257.117792  104.0
5    105.0  C  0.369257 2020-07-10    284.354928  105.0
6    106.0  D  0.615223 2020-07-11    172.295125  106.0
7    107.0  B  0.148601 2020-07-12    720.050346  107.0
8    108.0  B  0.707396 2020-07-13    152.672633  108.0
9    109.0  E  0.222646 2020-07-14    489.565612  109.0
100  110.0  Z  0.112233 2020-11-03           NaN    NaN

In [52]:
df.a ==df.F

0       True
1       True
2       True
3       True
4       True
5      False
6       True
7       True
8       True
9       True
100    False
dtype: bool

In [53]:
#Sorting
#sort_values and sort_index: return a new object; ascending=False for descending order
df.sort_values('c')

a  b         c          d             E      F
0    100.0  C  0.002056 2020-07-05  48632.335790  100.0
100  110.0  Z  0.112233 2020-11-03           NaN    NaN
7    107.0  B  0.148601 2020-07-12    720.050346  107.0
9    109.0  E  0.222646 2020-07-14    489.565612  109.0
3    103.0  C  0.256880 2020-07-08    400.965553  103.0
5    105.0  C  0.369257 2020-07-10    284.354928  105.0
4    104.0  C  0.404484 2020-07-09    257.117792  104.0
6    106.0  D  0.615223 2020-07-11    172.295125  106.0
8    108.0  B  0.707396 2020-07-13    152.672633  108.0
1    101.0  A  0.952524 2020-07-06    106.034037  101.0
2    102.0  E  0.960452 2020-07-07    106.200021  102.0

In [ ]:
def countstr(word):
    word.upper()

In [55]:
def word_count(s):
    """
    always document here!
    """
    word_list = s.lower().split()
    df = pd.DataFrame([[i, word_list.count(i)] for i in set(word_list)], columns=['word', 'freq'])
    return df
word_count('Hey mama hey papa')

word  freq
0  mama     1
1  papa     1
2   hey     2

In [58]:
def word_count_ex(s, excluded_chars='",\';:()[]!?@#$%&=\\.'):
    """"
    word counter with excluded characters
    """
    for i in excluded_chars:
        s = s.replace(i, ' ')
    # which is kinda yucky
    word_list = s.lower().split()
    df = pd.DataFrame([[i, word_list.count(i)] for i in set(word_list)], columns=['word', 'freq'])
    df['letters'] = df.word.str.len()
    df = df.sort_values('letters', ascending=False)
    return df

In [56]:
import requests

In [59]:
r = requests.get('http://www.mynl.com/RPM/di.txt')

di = r.text

print(di[:100])

df = word_count_ex(di)

df

Congress, July 4, 1776.
The unanimous Declaration of the thirteen united States of America, When in


word  freq  letters
241  undistinguished     1       15
144  representatives     1       15
85    unacknowledged     1       14
308   representative     1       14
313   appropriations     1       14
..               ...   ...      ...
214               as     4        2
432               is    10        2
385                4     1        1
33                 s     1        1
487                a    16        1

[541 rows x 3 columns]

In [60]:
df.sort_values('freq', ascending=False)

word  freq  letters
387               of    78        2
423              the    78        3
23                to    65        2
174              and    56        3
184              for    29        3
..               ...   ...      ...
526          example     1        7
144  representatives     1       15
176          publish     1        7
11           english     1        7
241  undistinguished     1       15

[541 rows x 3 columns]

In [ ]:
n_claims = 1000
loss = np.random.lognormal(10.1)
kind = np.random.choice([liab, pd, comp, coll])
open = 

In [ ]:
n = 1000
df = pd.DataFrame({'loss': np.random.lognormal(10,1,n),
                   'kind': np.random.choice(list('ABCDE'), n),
                   'open': np.random.binomial(1, 0.3, n)})
df.loc[df.kind=="A", "loss"] *= 1.95
df.loc[df.kind=="B", "loss"] *= 1.45
df.loc[df.kind=="D", "loss"] *= 0.95
df.loc[df.kind=="E", "loss"] *= 0.65
df['log_loss'] = np.log(df.loss)
df.head(10)
Module 4: 